### model
model_name_or_path: meta-llama/Llama-3.2-90B-Vision-Instruct
quantization_bit: 4
quantization_method: bitsandbytes
cache_dir: /workspace/huggingface

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: /workspace/llama_factory/app/mine/data
dataset: llava-zh-3k
template: mllama
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Llama-3.2-90B-Vision-Instruct/lora/sft/llava-zh-3k
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
