### model
model_name_or_path: meta-llama/Llama-3.2-90B-Vision-Instruct
quantization_bit: 4
quantization_method: bitsandbytes
cache_dir: /workspace/huggingface
trust_remote_code: true

### dataset
task: cmmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: zh
n_shot: 5

### output
save_dir: saves/Llama-3.2-90B-Vision-Instruct/base/eval/cmmlu_test

### eval
batch_size: 4

