### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
cache_dir: /workspace/modelscope
trust_remote_code: true

### dataset
task: cmmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: zh
n_shot: 5

### output
save_dir: saves/Qwen2.5-7B-Instruct/base/eval/cmmlu_test

### eval
batch_size: 4

